% generate_jetEngine_expected_values - Generate expected values from MATLAB for Python test
% This script runs the same computation as the Python test and saves expected values

% Add path to jetEngine hessian functions
addpath('cora_matlab/models/auxiliary/jetEngine');

% system dimension
dim_x = 2;

% parameters (EXACTLY matching original MATLAB example_nonlinear_reach_12_adaptive.m)
params.tFinal = 8;
params.R0 = zonotope([[1;1],0.1*diag(ones(dim_x,1))]);
params.U = zonotope(0);
% Note: params.tStart is not set in original example (defaults to 0)

% algorithm parameters (EXACTLY matching original MATLAB example)
% Original example only sets: options.alg = 'lin-adaptive';
% No progress, progressInterval, or verbose options
options.alg = 'lin-adaptive';

% init system
sys = nonlinearSys(@jetEngine,dim_x,1);

% run reachability analysis
fprintf('Generating MATLAB expected values for Python test...\n');
adapTime = tic;
[R,~,opt] = reach(sys,params,options);
tComp = toc(adapTime);

fprintf('MATLAB computation completed in %.2f seconds\n', tComp);

% Extract results (EXACTLY matching Python test extraction)
endset = R.timePoint.set{end};
gamma_o = 2*rad(interval(endset));

% Save expected values in a format Python can easily read
expected_values.numSteps = length(R.timePoint.set);
expected_values.finalTime = R.timePoint.time{end};
expected_values.finalRadius = max(gamma_o);
expected_values.options_alg = opt.alg;
expected_values.tComp = tComp;

% Also save the full results for detailed comparison
save('jetEngine_expected_values.mat', 'expected_values', 'R', 'opt', 'params', 'options');

% Print expected values for Python test
fprintf('\n=== EXPECTED VALUES FOR PYTHON TEST ===\n');
fprintf('expected_numSteps = %d\n', expected_values.numSteps);
fprintf('expected_finalTime = %.10f\n', expected_values.finalTime);
fprintf('expected_finalRadius = %.10e\n', expected_values.finalRadius);
fprintf('expected_alg = ''%s''\n', expected_values.options_alg);
fprintf('\n');

% Also write to a text file for easy copy-paste
fid = fopen('jetEngine_expected_values.txt', 'w');
fprintf(fid, '# Expected values from MATLAB for Python test\n');
fprintf(fid, '# Generated by generate_jetEngine_expected_values.m\n');
fprintf(fid, '# Input: params.tFinal=8.0, params.R0=zonotope([[1;1],0.1*diag(ones(2,1))]), options.alg=''lin-adaptive''\n');
fprintf(fid, '\n');
fprintf(fid, 'expected_numSteps = %d\n', expected_values.numSteps);
fprintf(fid, 'expected_finalTime = %.10f\n', expected_values.finalTime);
fprintf(fid, 'expected_finalRadius = %.10e\n', expected_values.finalRadius);
fprintf(fid, 'expected_alg = ''%s''\n', expected_values.options_alg);
fclose(fid);

fprintf('Expected values saved to:\n');
fprintf('  - jetEngine_expected_values.mat (MATLAB format)\n');
fprintf('  - jetEngine_expected_values.txt (text format)\n');
