"""
test_interval_plus - unit test function of plus (MATLAB parity)

Source MATLAB test:
`cora_matlab/unitTests/contSet/interval/test_interval_plus.m`

MATLAB I/O pairs generated by:
`debug_matlab_interval_plus.m`
Output file:
`matlab_interval_plus_output.txt`
"""

import numpy as np
import pytest
from cora_python.contSet import Interval, Zonotope


def _assert_interval_plus(lhs, rhs, expected, tol):
    assert (lhs + rhs).isequal(expected, tol)
    assert (rhs + lhs).isequal(expected, tol)


@pytest.mark.parametrize(
    "lhs, rhs, expected",
    [
        # bounded interval, numeric
        (Interval([-2, -1], [3, 4]), np.array([2, 1]), Interval([0, 0], [5, 5])),
        # unbounded interval, numeric
        (Interval([-np.inf], [2]), 1, Interval([-np.inf], [3])),
        # bounded interval, bounded interval
        (Interval([-2, -1], [3, 4]), Interval([-1, -3], [1, -1]), Interval([-3, -4], [4, 3])),
        # unbounded interval, unbounded interval
        (Interval([-np.inf, -2], [2, 4]), Interval([-1, 0], [1, np.inf]), Interval([-np.inf, -2], [3, np.inf])),
        # interval matrix, numeric
        (Interval([[-2, -1], [0, 2]], [[3, 5], [2, 3]]), 2, Interval([[0, 1], [2, 4]], [[5, 7], [4, 5]])),
        # scalar operations
        (Interval([-1, 0], [2, 3]), 5, Interval([4, 5], [7, 8])),
        # vector operations
        (Interval([-1, 0], [2, 3]), np.array([1, -1]), Interval([0, -1], [3, 2])),
        # matrix operations (interval + interval)
        (Interval([[-1, 0], [1, -1]], [[2, 1], [3, 2]]),
         Interval([[0, -1], [-1, 0]], [[1, 0], [2, 1]]),
         Interval([[-1, -1], [0, -1]], [[3, 1], [5, 3]])),
        # zero operations
        (Interval([-1, 0], [2, 3]), 0, Interval([-1, 0], [2, 3])),
        (Interval([-1, 0], [2, 3]), np.zeros(2), Interval([-1, 0], [2, 3])),
    ],
)
def test_interval_plus_interval_and_numeric(lhs, rhs, expected):
    """MATLAB-verified interval + interval/numeric cases."""
    _assert_interval_plus(lhs, rhs, expected, 1e-9)


def test_interval_plus_empty_interval():
    """MATLAB-verified empty interval case."""
    I = Interval.empty(1)
    v = 1
    assert (I + v).representsa_('emptySet')
    assert (v + I).representsa_('emptySet')


def test_interval_plus_associativity():
    """MATLAB-verified associativity case."""
    I1 = Interval([-1, 0], [1, 2])
    I2 = Interval([0, -1], [2, 1])
    I3 = Interval([-1, -1], [1, 1])
    expected = Interval([-2, -2], [4, 4])
    assert ((I1 + I2) + I3).isequal(expected, 1e-9)
    assert (I1 + (I2 + I3)).isequal(expected, 1e-9)


@pytest.mark.parametrize(
    "interval, zonotope, expected",
    [
        # interval + zonotope
        (Interval([-1, -1], [1, 1]),
         Zonotope(np.array([[0], [0]]), np.array([[1, 0], [0, 1]])),
         Zonotope(np.array([[0], [0]]), np.array([[1, 0, 1, 0], [0, 1, 0, 1]]))),
        # interval + zonotope different shapes
        (Interval([0, -2], [2, 1]),
         Zonotope(np.array([[1], [-1]]), np.array([[0.5, 0], [0, 0.5]])),
         Zonotope(np.array([[2], [-1.5]]), np.array([[0.5, 0, 1, 0], [0, 0.5, 0, 1.5]]))),
        # interval + zonotope 1d
        (Interval([-2], [3]),
         Zonotope(np.array([[1]]), np.array([[2]])),
         Zonotope(np.array([[1.5]]), np.array([[2, 2.5]]))),
        # interval + zonotope point
        (Interval([-1, 0], [1, 2]),
         Zonotope(np.array([[2], [1]])),
         Zonotope(np.array([[2], [2]]), np.array([[1, 0], [0, 1]]))),
        # interval + zonotope empty (MATLAB: c is zeros(2,0))
        (Interval.empty(2),
         Zonotope(np.array([[0], [0]]), np.array([[1, 0], [0, 1]])),
         Zonotope(np.zeros((2, 0)), np.array([[1, 0], [0, 1]]))),
    ],
)
def test_interval_plus_zonotope_cases(interval, zonotope, expected):
    """MATLAB-verified interval + zonotope cases (result is zonotope)."""
    tol = 1e-9
    assert (interval + zonotope).isequal(expected, tol)
    assert (zonotope + interval).isequal(expected, tol)
